### ISSUE TITLE
Test plan for Org View

### ISSUE THREAD

**Issue by levity** [coordinape/coordinape#727]
- review new main nav
  - check out different screen sizes & the way text wraps
- review new overview page
  - try creating a circle through the add circle button
  - make sure hover buttons work correctly & navigate to the correct locations 
- review new history page
  - try viewing received & sent notes
    - make sure avatars still display correctly
    - are changes to notes look & feel ok?
  - use pagination buttons
- notice if any pages are very slow to load
- do a quick browse through the rest of the app, make sure nothing's broken

**Comment by reeserj** [comment]
> review new main nav
> - check out different screen sizes & the way text wraps

When Screen is narrowed down the buttons on circles don't resize or shrink for you 
![image](https://user-images.githubusercontent.com/82838264/161355424-9e714de7-14ef-4245-bcfb-4a8584f8bb99.png)
There's a small width window between when it switches to the mobile layout and when it goes from desktop width where you can't click on your pfp for the drop down window (Under 960 px and greater than 900px) 
![image](https://user-images.githubusercontent.com/82838264/161355581-a50f09f7-b465-4626-8ee8-c968aab1e9e2.png)

On the mobile layout we have - Circles, history, allocate, map, my profile, and docs
On the desktop layout we have - Circles, history (via the give tracker), then under the pfp, my profile, docs and give feedback.

![image](https://user-images.githubusercontent.com/82838264/161355772-f55679b8-319d-4501-83e8-40d63b620f02.png)
![image](https://user-images.githubusercontent.com/82838264/161355787-92368ae0-172d-4a7c-9b4a-470a69740317.png)
I think these need to be reconciled, I'm partial to keeping more information in the pfp dropdown as it consolidates the navigation to one spot. But I'll defer to the design team on that decision. 

> review new overview page
> - try creating a circle through the add circle button

Working as expected. but when we go back to the circles to see the circle I created after creating an epoch Epoch # 1 doesn't have the number show up like it does for other epochs 
![image](https://user-images.githubusercontent.com/82838264/161355483-4b3c338d-1d99-4565-b282-d6445da177b9.png)

> make sure hover buttons work correctly & navigate to the correct locations

These worked as expected, I think we need to tweak the "Add Contributor" Tooltip though.  Kudos reminds me of https://gitcoin.co/kudos

**A member of a circle that can receive give or kudos for contributions performed**
_A member of a circle who may be eligible to send and receive GIVE or Notes for  their contributions_

> review new history page

> - try viewing received & sent notes

My first instinct was to click on the whole section to expand it to see my notes, the "See more" section wasn't the most intuitive.

![image](https://user-images.githubusercontent.com/82838264/161356517-49b2165c-03d6-4642-ba8b-683d12f6f50f.png)

When sized down to mobile you can't see your notes at all, the date portion doesn't resize to accommodate the smaller screen. 

I'd recommend moving the dates above and shrinking the font when the screen gets small.

![image](https://user-images.githubusercontent.com/82838264/161356571-a659424d-058e-466b-a433-33ca5ae22f85.png)``

Also when sized between 900 px and 1080px the header doesn't resize appropriately

![image](https://user-images.githubusercontent.com/82838264/161356933-e7028feb-f1d8-47d0-8438-29f2109b5729.png)

> - make sure avatars still display correctly

Working

>  are changes to notes look & feel ok?

I like the Change!

> - use pagination buttons

They resize well, and work well.

> notice if any pages are very slow to load

switching wallets took a while going from Metamask to Walletconnect no delay going from walletconnect to Coinbase Wallet though

> do a quick browse through the rest of the app, make sure nothing's broken

The Circle navigation name needs to be aware of the header bar so they don't extend over it's bar.

![image](https://user-images.githubusercontent.com/82838264/161357223-4dce2dd8-5ce4-4701-94e0-6adb563e409f.png)

If we shrink the screen down too narrow on the map screen you can't see anything and can't see the arrow to close the user tab and see the map 

![image](https://user-images.githubusercontent.com/82838264/161357370-e39d26c5-4c3e-41f2-aeb4-ee93d9ed3030.png)

**Comment by levity** [comment]
Thanks, @reeserj!

### TODO
- [ ] There's a small width window between when it switches to the mobile layout and when it goes from desktop width where you can't click on your pfp for the drop down window (Under 960 px and greater than 900px)
- [ ] When Screen is narrowed down the buttons on circles don't resize or shrink for you
- [ ] When sized down to mobile you can't see your notes at all
- [ ] My first instinct was to click on the whole section to expand it to see my notes, the "See more" section wasn't the most intuitive
- [ ] when sized between 900 px and 1080px the header doesn't resize appropriately

### won't fix (out of scope, low priority, etc)
- [ ] If we shrink the screen down too narrow on the map screen you can't see anything and can't see the arrow to close the user tab and see the map
- [ ] I think the [mobile and desktop nav links] need to be reconciled
- [ ] after creating an epoch Epoch # 1 doesn't have the number show up like it does for other epochs
  - this one's interesting... the number is assigned by the backend later, i believe, so there's a bit of lag. not much we can do from the FE to change this. maybe the backend could be modified to assign this during the original epoch creation? @zashton @topocount @CryptoGraffe

**Comment by levity** [comment]
@smombartz see above -- on smaller screens, it's easy to run out of horizontal space in the navbar. i couldn't find a simple-&-easy solution I liked, so I wanted to ask you how to proceed.

**Comment by Zemm111** [comment]
- review new main nav
-- <img width="196" alt="image" src="https://user-images.githubusercontent.com/71293476/161670423-8335e05a-aec8-47f0-b426-061d75c75e4f.png">
-- The use of a carrot here seems a little odd / sloppy to me in context here, not sure what would be better, a dash?  a comma?  one of these: | ?


- review new overview page
-- <img width="203" alt="image" src="https://user-images.githubusercontent.com/71293476/161670818-821e5d9d-6166-4474-9034-f3064c5b1f34.png">
-- Feel like the circle and org should have different font sizes here to help differentiate.  
-- In general these fonts seem too large on my screen (2560-by-1600 MacBook Air).  When I go down to 80% scale on my browser they look OK.
-- Maybe NBD, but could the Circle Logo be used here to help quickly identify columns? 
-- <img width="210" alt="image" src="https://user-images.githubusercontent.com/71293476/161673089-4e821071-88d5-4d9c-bf9b-f27e130d529c.png">
-- Could the "Circle Admin" label be a bit further from the Circle Name?  
-- Should clicking on it go to the Admin area?  That was my assumption, since its blue.
-- This page doesn't use the same salmony red at all that the rest of our app uses pretty regularly, so it feels a bit discontinuous.  

- try creating a circle through the add circle button
-- <img width="400" alt="image" src="https://user-images.githubusercontent.com/71293476/161671181-48aa5a67-d7fd-43f6-bf56-7f1a0f966bf3.png">
-- for some reason the Username field remembers wallet addresses I've used in the past (?). Using Brave.

- make sure hover buttons work correctly & navigate to the correct locations
-- They work!  Are they supposed to disappear unless you hover over them?

- review new history page
-- works well!
-- This page doesn't use the same salmony red much that the rest of our app uses pretty regularly, so it feels a bit discontinuous.  

- try viewing received & sent notes
-- works well! 

- make sure avatars still display correctly
-- √

- are changes to notes look & feel ok?
-- Do wonder if "Show More" should just say "Show Notes", since that's what it does : )
-- When you have a lot of notes in a big circle pop up, the "show less" button goes way down to the bottom of the list.  Might be better if it justifies to the top so that you don't think it just disappeared.

-use pagination buttons
-- works well, hard to notice them on small screens as the four History rows push it below my screen's height.

- notice if any pages are very slow to load
-- Seems OK

- do a quick browse through the rest of the app, make sure nothing's broken
-- Save button on Profile does not

**Comment by zashton** [comment]
>   * this one's interesting... the number is assigned by the backend later, i believe, so there's a bit of lag. not much we can do from the FE to change this. maybe the backend could be modified to assign this during the original epoch creation? @zashton @topocount @CryptoGraffe
> 
> ### will discuss with design team
> * [ ]  when sized between 900 px and 1080px the header doesn't resize appropriately

Yeah should be possible to set the epoch number upon creation, but the number is not definitive until the epoch starts as it relies on the date chronological order, admin could create/delete/update another epoch before it and the numbers for all the upcoming epoch will be changed again.
@levity

**Comment by levity** [comment]
Tweaks from Sascha's review:

- [ ] move breadcrumb above circle-specific links
- [ ] double-check stopping autocomplete on org name field
- [ ] open New Epoch modal from circle history?
- [ ] make Circle Admin grey12 / placeholder
- [ ] move Show More/Less into notes panel
- [ ] make clicking on circles row go to history

**Comment by Zemm111** [comment]
@spydermonkee I tried updating the name of a circle on the vercel test for this ticket, and got the following error.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/71293476/161847702-a645088b-c2e8-423c-8840-884cddfd944d.png">

**Comment by levity** [comment]
> @spydermonkee I tried updating the name of a circle on the vercel test for this ticket, and got the following error. <img alt="image" width="474" src="https://user-images.githubusercontent.com/71293476/161847702-a645088b-c2e8-423c-8840-884cddfd944d.png">

ahh, i think this is because the staging env is a bit behind main, so it's missing some migrations. thanks for catching that, should be fixed in 15m

**Comment by reeserj** [comment]
Are we good to close this now @levity
